spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/crud_project?useSSL=false
      username: postgres
      password: postgre2023
  jpa: 
    open-in-view: false
    hibernate: 
      ddl-auto: none
    show-sql: false
        
