cors:
  origenPatterns: http://localhost:3000,http://localhost:8080,https://erudio.com.br
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 360000
spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/crud_project?useSSL=false
      username: postgres
      password: postgre2023
  jpa: 
    open-in-view: false
    hibernate: 
      ddl-auto: update
    show-sql: false
        
springdoc:
  paths-to-match: 
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true